name: Sample Builder Workflow for Docker Images for User code

on:
  workflow_dispatch:
    inputs:
      function_exports_path_in_repo:
        type: string
        required: true
        description: Path of file that exports your functions
      function_name:
        type: string
        required: true
        description: Function name to deploy from source code
      aws_region:
        type: string
        required: true
        default: ap-south-1
        description: AWS Region ID
      aws_key_id:
        type: string
        required: true
        description: AWS Key ID of your account with access to AWS ECR
      aws_secret_access_key:
        type: string
        required: true
        description: AWS Secret Access Key of your account with access to AWS ECR
      aws_ecr_repo_name:
        type: string
        required: true
        description: Name Of AWS ECR Repository

jobs:
  Build-And-Push-Image:
    name: Builds and Pushes Docker Image to AWS ECR
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup AWS ECR Details
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_key_id }}
          aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
          aws-region: ${{ inputs.aws_region }}

      - name: Login to Amazon ECR
        id: login-to-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push the tagged docker image to Amazon ECR
        working-directory: ./builder
        env:
          ECR_REGISTRY: ${{ steps.login-to-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.aws_ecr_repo_name }}
          FUNCTIONS_EXPORT_PATH: ${{ inputs.function_exports_path_in_repo }}
          FUNCTION_NAME: ${{ inputs.function_name }}
          DOCKER_IMAGE_FULL_TAG: ${{ steps.login-to-aws-ecr.outputs.registry }}/${{ inputs.aws_ecr_repo_name }}:${{ inputs.function_name }}
        run: |
          node generate-builder-and-dockerfile $FUNCTIONS_EXPORT_PATH $FUNCTION_NAME $DOCKER_IMAGE_FULL_TAG
          sh ./build.sh
          docker push $DOCKER_IMAGE_FULL_TAG
